services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    depends_on:
      - db
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:3000/api}

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: musical_group
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
